// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaDbc2I_1n2dwcm1qxtqfilq2IjFhhGok',
    appId: '1:767227560932:web:331bacb5099ed91f6bfdf1',
    messagingSenderId: '767227560932',
    projectId: 'infernocore-6721c',
    authDomain: 'infernocore-6721c.firebaseapp.com',
    storageBucket: 'infernocore-6721c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmynnQrcejWa1d-LzL9DMCARv-Woiy58',
    appId: '1:767227560932:android:c874fddfa1c5745e6bfdf1',
    messagingSenderId: '767227560932',
    projectId: 'infernocore-6721c',
    storageBucket: 'infernocore-6721c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxsONkhAxNfmRikbryHPuUrGy9a7VMQ0A',
    appId: '1:767227560932:ios:a7f1dd2253f3e2306bfdf1',
    messagingSenderId: '767227560932',
    projectId: 'infernocore-6721c',
    storageBucket: 'infernocore-6721c.appspot.com',
    iosClientId: '767227560932-huuajbkt3ed6d9jqd2mc5ek9g7gblp07.apps.googleusercontent.com',
    iosBundleId: 'com.example.infernoCoreFyp',
  );
}
